export const CONFIG = {
  TIMEOUT_NWC_CONNECT_MS: 10000,
  TIMEOUT_PAYMENT_MS: 20000,
};

export const UI_STATES = {
  IDLE: 'IDLE',
  SCANNING: 'SCANNING',
  CONNECTING_WALLET: 'CONNECTING_WALLET',
  REQUESTING_INVOICE: 'REQUESTING_INVOICE',
  PAYING: 'PAYING',
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR'
};
